### ISSUE TITLE
ncpmount cannot find server

### ISSUE THREAD

**Issue by phdru** [EnzephaloN/ncpfs_dkms#2]
`ncpmount` reports "Cannot find server". 

Does the module implement IPX/SPX protocols? I suspect no and latest kernels (>= 4.18) got rid of these protocols.

How I can re-add the protocols back to my kernels?

**Comment by EnzephaloN** [comment]
Hello @phdru 
As support for ncpfs (and IPX) was dropped by the kernel, I asked the kernel-mailinglist for bringing it back. They told me to maintain it by myself, because they have noone for doing this.
So some peers and I patched NCPFS for our uses.
Because we do not need (and have no IPX-network), we do not maintain/patch IPX-kernel-modules.
Maybe you try by yourself. Grab your kernelsources and try to compile the latest IPX-sources you can find and then patch the upcoming errors.
Good luck.
